import { ArrowLeft, MessageCircle, Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";
import { Link } from "react-router-dom";
import { PageMeta } from "../components/PageMeta";
import { useCart } from "../context/CartContext";
import { cartWhatsappUrl, formatPrice, imageUrl } from "../lib/site";

export default function Cart() {
  const { items, totalItems, knownTotal, hasUnknownPrices, updateQuantity, removeItem, clearCart } = useCart();
  if (!items.length) return <div className="page-shell container"><PageMeta title="Sepetim" description="İlgün Ticaret ürün sepeti" canonical="/cart"/><div className="empty-cart"><span><ShoppingBag/></span><h1>Sepetiniz boş</h1><p>İlgilendiğiniz ürünleri sepete ekleyip tek mesajla bilgi ve fiyat isteyebilirsiniz.</p><Link className="button primary" to="/products">Ürünleri İncele</Link></div></div>;
  const orderUrl = cartWhatsappUrl(items);
  return <div className="page-shell container cart-page"><PageMeta title={`Sepetim (${totalItems})`} description="İlgün Ticaret WhatsApp sipariş sepeti" canonical="/cart"/><div className="cart-heading"><div><span className="eyebrow">SEPETİM</span><h1>{totalItems} ürün seçtiniz</h1><p>Adetleri düzenleyin ve listenizi WhatsApp üzerinden gönderin.</p></div><button onClick={clearCart}><Trash2/> Sepeti Temizle</button></div><div className="cart-layout"><div className="cart-items">{items.map(({ product, quantity }) => <article className="cart-item" key={product.id}><Link to={`/products/${product.slug}`}><img src={imageUrl(product.main_image)} alt={product.name}/></Link><div className="cart-item-info"><span>{product.brand || "İlgün Seçkisi"} · {product.model}</span><Link to={`/products/${product.slug}`}><strong>{product.name}</strong></Link><b>{formatPrice(product.price, product.currency)}</b></div><div className="quantity-control" aria-label={`${product.name} adedi`}><button onClick={() => updateQuantity(product.id, quantity - 1)} aria-label="Azalt"><Minus/></button><span>{quantity}</span><button onClick={() => updateQuantity(product.id, quantity + 1)} aria-label="Artır"><Plus/></button></div><button className="remove-item" onClick={() => removeItem(product.id)} aria-label={`${product.name} sepetten çıkar`}><Trash2/></button></article>)}</div><aside className="order-summary"><h2>Sipariş özeti</h2><div><span>Ürün adedi</span><strong>{totalItems}</strong></div>{knownTotal > 0 && <div><span>Bilinen fiyatlar toplamı</span><strong>{formatPrice(knownTotal)}</strong></div>}{hasUnknownPrices && <p>Bazı ürünlerin fiyatı için iletişime geçilmesi gerekiyor. Güncel fiyat ve stok mesajınıza yanıt olarak iletilecektir.</p>}<a className="button whatsapp" href={orderUrl} target="_blank" rel="noreferrer"><MessageCircle/> WhatsApp'tan Sipariş Ver</a><Link className="continue-shopping" to="/products"><ArrowLeft/> Alışverişe devam et</Link></aside></div><div className="mobile-cart-order"><a className="button whatsapp" href={orderUrl} target="_blank" rel="noreferrer"><MessageCircle/> WhatsApp'a Gönder · {totalItems} ürün</a></div></div>;
}
